### ISSUE TITLE
Medefaidrin font keyboard

### ISSUE THREAD

**Issue by SheriMango** [notofonts/medefaidrin#2]
Sans Noto Medefaidrin is available on Google Fonts but when downloaded and used only Latin letters appear. 
How do I get a Medefaidrin font with Medefaidrin characters I can type on Word, Google Docs etc?
A keyboard with the characters would be very useful for typing like a Keyman keyboard.

**Comment by mi2ebi** [comment]
all the medefaidrin letters in the font are at their proper codepoints: https://unicode.org/charts/PDF/U16E40.pdf

**Comment by mi2ebi** [comment]
(and noto doesn't make keyboard layouts)

**Comment by simoncozens** [comment]
Yes, this is out of scope for the Noto project. You can certainly make one yourself with Keyman.
